/*
 * This source file was generated by the Gradle 'init' task
 */
package org.valueatrisk;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.List;
import java.util.stream.Collectors;

public class ValueAtRiskMain {

    public static void main(String[] args) {
        System.out.println("-----BEGIN-----");
        System.out.println("Running Value At Risk calculator");
        if (args.length != 2) {
            System.err.println("Usage: java ValueAtRiskMain <confidence_level> <input_file>");
            System.err.println("Example: java ValueAtRiskMain 0.95 trades.txt");
            System.exit(1);
        }

        ValueAtRiskService varService = new ValueAtRiskService();
        TradeFileReaderService readerService = new TradeFileReaderService();

        try {
            BigDecimal confidenceLvl = new BigDecimal(args[0]);
            String filePath = args[1];

            List<Trade> trades = readerService.readTradesFromFile(filePath);

            if (trades.size() == 1) {
                System.out.println("Single trade VaR calculation");
                Trade trade = trades.get(0);
                BigDecimal var = varService.getTradeVaR(confidenceLvl, trade);

                System.out.printf("VaR for trade with id: %s is %s \n",trade.id(), var);
            } else {
                System.out.println("Portfolio VaR calculation");
                BigDecimal portfolioVar = varService.getPortfolioVaR(confidenceLvl, trades);
                System.out.printf("VaR for portfolio is %s \n", portfolioVar);
                
                // List<BigDecimal> individualVars = trades.stream()
                //         .map(t -> {
                //             BigDecimal tradeVar = varService.getTradeVaR(confidenceLvl, t);
                //             return tradeVar;
                //         })
                //         .collect(Collectors.toList());
                
                // BigDecimal sumIndividualVars = individualVars.stream()
                //         .reduce(BigDecimal.ZERO, BigDecimal::add);
                
                // System.out.printf("Sum of individual VaR for portfolio is %s \n", sumIndividualVars);
                System.out.println("-----END-----");
            }
        } catch (IOException e) {
            System.err.println("Error reading file: " + e.getMessage());
            System.exit(1);
        } catch (IllegalArgumentException e) {
            System.err.println("Error: " + e.getMessage());
            System.exit(1);
        }
    }
}

